name: run_tests

on:
  pull_request:
  push:
    branches:
      - rezed
      - main
  workflow_dispatch:

concurrency:
  group: run-tests-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"
  CARGO_INCREMENTAL: "0"

jobs:
  style:
    name: Style
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: rustup show
      - name: Check Rust formatting
        run: cargo fmt --all -- --check

  linux-check:
    name: Linux check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Linux dependencies
        run: ./script/linux
      - name: Install WASI SDK
        run: ./script/download-wasi-sdk
      - name: Check app crates
        run: cargo check --locked --package zed --package cli --package remote_server

  release-channel-tests:
    name: Release channel tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run release channel tests
        run: cargo test --locked --package release_channel
